package com.hmsa.pharma.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 15 23:56:48 AST 2018
// ---------------------------------------------------------------------
public interface PharmaAM extends ApplicationModule {
    Boolean validateDuesAgingIntersection();

    String selectAll(String instanceName);

    String removeAll(String instanceName);
}

