package com.hmsa.pharma.model.cfg.vo.up;

import com.hmsa.checkpoint.basic.classes.CheckpointEntityImpl;
import com.hmsa.checkpoint.basic.classes.CheckpointViewRowImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 15 23:57:21 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CfgDuesAgingViewRowImpl extends CheckpointViewRowImpl {
    public static final int ENTITY_CFGDUESAGING = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        FromDaysNo,
        ToDaysNo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int FROMDAYSNO = AttributesEnum.FromDaysNo.index();
    public static final int TODAYSNO = AttributesEnum.ToDaysNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CfgDuesAgingViewRowImpl() {
    }

    /**
     * Gets CfgDuesAging entity object.
     * @return the CfgDuesAging
     */
    public CheckpointEntityImpl getCfgDuesAging() {
        return (CheckpointEntityImpl) getEntity(ENTITY_CFGDUESAGING);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Gets the attribute value for FROM_DAYS_NO using the alias name FromDaysNo.
     * @return the FROM_DAYS_NO
     */
    public Number getFromDaysNo() {
        return (Number) getAttributeInternal(FROMDAYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_DAYS_NO using the alias name FromDaysNo.
     * @param value value to set the FROM_DAYS_NO
     */
    public void setFromDaysNo(Number value) {
        setAttributeInternal(FROMDAYSNO, value);
    }

    /**
     * Gets the attribute value for TO_DAYS_NO using the alias name ToDaysNo.
     * @return the TO_DAYS_NO
     */
    public Number getToDaysNo() {
        return (Number) getAttributeInternal(TODAYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_DAYS_NO using the alias name ToDaysNo.
     * @param value value to set the TO_DAYS_NO
     */
    public void setToDaysNo(Number value) {
        setAttributeInternal(TODAYSNO, value);
    }
}

