package com.hmsa.pharma.model.rtx.vo.up;

import com.hmsa.checkpoint.basic.classes.CheckpointEntityImpl;
import com.hmsa.checkpoint.basic.classes.CheckpointViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 17 01:35:03 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrxDailySalesViewRowImpl extends CheckpointViewRowImpl {
    public static final int ENTITY_TRXDAILYSALES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TrxId,
        TrxCode,
        TrxDate,
        TrxType,
        CustomerId,
        ItemId,
        UnitId,
        Price,
        Quantity,
        Amount,
        CreateDate,
        CreatedBy,
        ModifyDate,
        ModifiedBy,
        DailySalesStaticLOV1,
        LkbCustomersROView1,
        UnitsOfItemsROView1,
        LkbItemsROView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TRXID = AttributesEnum.TrxId.index();
    public static final int TRXCODE = AttributesEnum.TrxCode.index();
    public static final int TRXDATE = AttributesEnum.TrxDate.index();
    public static final int TRXTYPE = AttributesEnum.TrxType.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int UNITID = AttributesEnum.UnitId.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int MODIFYDATE = AttributesEnum.ModifyDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int DAILYSALESSTATICLOV1 = AttributesEnum.DailySalesStaticLOV1.index();
    public static final int LKBCUSTOMERSROVIEW1 = AttributesEnum.LkbCustomersROView1.index();
    public static final int UNITSOFITEMSROVIEW1 = AttributesEnum.UnitsOfItemsROView1.index();
    public static final int LKBITEMSROVIEW1 = AttributesEnum.LkbItemsROView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TrxDailySalesViewRowImpl() {
    }

    /**
     * Gets TrxDailySales entity object.
     * @return the TrxDailySales
     */
    public CheckpointEntityImpl getTrxDailySales() {
        return (CheckpointEntityImpl) getEntity(ENTITY_TRXDAILYSALES);
    }

    /**
     * Gets the attribute value for TRX_ID using the alias name TrxId.
     * @return the TRX_ID
     */
    public Number getTrxId() {
        return (Number) getAttributeInternal(TRXID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_ID using the alias name TrxId.
     * @param value value to set the TRX_ID
     */
    public void setTrxId(Number value) {
        setAttributeInternal(TRXID, value);
    }

    /**
     * Gets the attribute value for TRX_CODE using the alias name TrxCode.
     * @return the TRX_CODE
     */
    public String getTrxCode() {
        return (String) getAttributeInternal(TRXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_CODE using the alias name TrxCode.
     * @param value value to set the TRX_CODE
     */
    public void setTrxCode(String value) {
        setAttributeInternal(TRXCODE, value);
    }

    /**
     * Gets the attribute value for TRX_DATE using the alias name TrxDate.
     * @return the TRX_DATE
     */
    public Date getTrxDate() {
        return (Date) getAttributeInternal(TRXDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_DATE using the alias name TrxDate.
     * @param value value to set the TRX_DATE
     */
    public void setTrxDate(Date value) {
        setAttributeInternal(TRXDATE, value);
    }

    /**
     * Gets the attribute value for TRX_TYPE using the alias name TrxType.
     * @return the TRX_TYPE
     */
    public Number getTrxType() {
        return (Number) getAttributeInternal(TRXTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_TYPE using the alias name TrxType.
     * @param value value to set the TRX_TYPE
     */
    public void setTrxType(Number value) {
        setAttributeInternal(TRXTYPE, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for UNIT_ID using the alias name UnitId.
     * @return the UNIT_ID
     */
    public Number getUnitId() {
        return (Number) getAttributeInternal(UNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_ID using the alias name UnitId.
     * @param value value to set the UNIT_ID
     */
    public void setUnitId(Number value) {
        setAttributeInternal(UNITID, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public Number getPrice() {
        return (Number) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(Number value) {
        setAttributeInternal(PRICE, value);
        if(value != null && getQuantity() != null){
            setAmount(value.multiply(getQuantity()));
        }
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
        if(value != null && getPrice() != null){
            setAmount(value.multiply(getPrice()));
        }
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @return the MODIFY_DATE
     */
    public Date getModifyDate() {
        return (Date) getAttributeInternal(MODIFYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @param value value to set the MODIFY_DATE
     */
    public void setModifyDate(Date value) {
        setAttributeInternal(MODIFYDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DailySalesStaticLOV1.
     */
    public RowSet getDailySalesStaticLOV1() {
        return (RowSet) getAttributeInternal(DAILYSALESSTATICLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LkbCustomersROView1.
     */
    public RowSet getLkbCustomersROView1() {
        return (RowSet) getAttributeInternal(LKBCUSTOMERSROVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UnitsOfItemsROView1.
     */
    public RowSet getUnitsOfItemsROView1() {
        return (RowSet) getAttributeInternal(UNITSOFITEMSROVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LkbItemsROView1.
     */
    public RowSet getLkbItemsROView1() {
        return (RowSet) getAttributeInternal(LKBITEMSROVIEW1);
    }
}

