package com.hmsa.pharma.model.rtn.vo.ro;

import com.hmsa.checkpoint.basic.classes.CheckpointViewRowImpl;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 16 22:44:35 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RepsCustomersROViewRowImpl extends CheckpointViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RowNumber,
        RepId,
        RepName,
        CustomerId,
        CustomerName,
        Exist,
        LkbRepsView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return RepsCustomersROViewRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return RepsCustomersROViewRowImpl.AttributesEnum.firstIndex() + RepsCustomersROViewRowImpl.AttributesEnum
                                                                                                      .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = RepsCustomersROViewRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ROWNUMBER = AttributesEnum.RowNumber.index();
    public static final int REPID = AttributesEnum.RepId.index();
    public static final int REPNAME = AttributesEnum.RepName.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int EXIST = AttributesEnum.Exist.index();
    public static final int LKBREPSVIEW = AttributesEnum.LkbRepsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RepsCustomersROViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute RowNumber.
     * @return the RowNumber
     */
    public Number getRowNumber() {
        return (Number) getAttributeInternal(ROWNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute RepId.
     * @return the RepId
     */
    public Number getRepId() {
        return (Number) getAttributeInternal(REPID);
    }

    /**
     * Gets the attribute value for the calculated attribute RepName.
     * @return the RepName
     */
    public String getRepName() {
        return (String) getAttributeInternal(REPNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute Exist.
     * @return the Exist
     */
    public Boolean getExist() {
        return (Boolean) getAttributeInternal(EXIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Exist.
     * @param value value to set the  Exist
     */
    public void setExist(Boolean value) {
        setAttributeInternal(EXIST, value);
        ViewObject vo = this.getApplicationModule().findViewObject("RtnRepsCustomersView");
        if(value != null && value){
            Row row = vo.createRow();
            row.setAttribute("RepId", getRepId());
            row.setAttribute("CustomerId", getCustomerId());
            vo.insertRow(row);
        }else{
            Key key = new Key(new Object[] { getRepId(), getCustomerId() });
            Row row = vo.findByKey(key, 1)[0];
            row.remove();
        }
    }

    /**
     * Gets the associated <code>CheckpointViewRowImpl</code> using master-detail link LkbRepsView.
     */
    public CheckpointViewRowImpl getLkbRepsView() {
        return (CheckpointViewRowImpl) getAttributeInternal(LKBREPSVIEW);
    }

    /**
     * Sets the master-detail link LkbRepsView between this object and <code>value</code>.
     */
    public void setLkbRepsView(CheckpointViewRowImpl value) {
        setAttributeInternal(LKBREPSVIEW, value);
    }
}

